# Test generated by RoostGPT for test dm-example-6 using AI Model gpt

import unittest
from unittest.mock import patch

# Check if the necessary modules are installed
try:
    from cloudant.client import Cloudant
except ImportError:
    print("Cloudant module not found. Please install it using pip install cloudant")

class TestCloudantClient:
    def disconnect(self):
        return True

# Mocking the cloudant_client
cloudant_client = TestCloudantClient()

def python_shutting_down():
    print('Disconnecting cloudant client')
    cloudant_client.disconnect()

class TestPythonShuttingDown(unittest.TestCase):

    @patch('builtins.print')
    def test_python_shutting_down_success(self, mock_print):
        try:
            python_shutting_down()
        except Exception as e:
            self.fail(f'Test failed due to: {e}')

        mock_print.assert_called_with('Disconnecting cloudant client')

    @patch('builtins.print')
    def test_python_shutting_down_failure(self, mock_print):
        with patch.object(cloudant_client, 'disconnect', side_effect=Exception('Failed to disconnect')):
            with self.assertRaises(Exception) as context:
                python_shutting_down()

            self.assertTrue('Failed to disconnect' in str(context.exception))

if __name__ == '__main__':
    unittest.main()
