# Test generated by RoostGPT for test dm-example-6 using AI Model gpt

import unittest
from unittest.mock import patch
from io import StringIO
from . import app

def python_shutting_down():
    print('Disconnecting redis client')
    # TODO

class TestPythonShuttingDown(unittest.TestCase):
    
    @patch('sys.stdout', new_callable=StringIO)
    def test_python_shutting_down(self, mock_stdout):
        python_shutting_down()
        self.assertEqual(mock_stdout.getvalue(), 'Disconnecting redis client\n')

    @patch('sys.stdout', new_callable=StringIO)
    def test_python_shutting_down_failure(self, mock_stdout):
        python_shutting_down()
        self.assertNotEqual(mock_stdout.getvalue(), 'Connecting redis client\n')

if __name__ == '__main__':
    unittest.main()
