# Test generated by RoostGPT for test dm-example-6 using AI Model gpt

import unittest
import redis
from unittest.mock import patch

class TestGetNextUserId(unittest.TestCase):

    @patch('redis.hincrby')
    def test_get_next_user_id_success(self, mock_redis):
        # Mocking the redis.hincrby method to return a successful response
        mock_redis.return_value = 1001

        from your_module import get_next_user_id  # Import your method here
        response = get_next_user_id()
        
        self.assertEqual(response, 1001, "The user_id should be 1001")

    @patch('redis.hincrby')
    def test_get_next_user_id_failure(self, mock_redis):
        # Mocking the redis.hincrby method to throw an exception
        mock_redis.side_effect = redis.exceptions.RedisError

        from your_module import get_next_user_id  # Import your method here
        with self.assertRaises(redis.exceptions.RedisError):
            get_next_user_id()

if __name__ == '__main__':
    unittest.main()
