# Test generated by RoostGPT for test dm-example-6 using AI Model gpt

import pytest
from flask import Flask, render_template
from flask.testing import FlaskClient

def create_app():
    app = Flask(__name__)

    @app.route('/error')
    def error_page():
        return render_template('404.html'), 404

    return app

@pytest.fixture
def client():
    app = create_app()
    app.testing = True
    client = app.test_client()

    return client

def test_page_not_found(client: FlaskClient):
    response = client.get('/error')
    assert response.status_code == 404

def test_page_not_found_content(client: FlaskClient):
    response = client.get('/error')
    assert b'404' in response.data   # Assuming '404' is in the 404.html template
